# Generated by Django 3.1.2 on 2020-11-18 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_email_max_length'),
        ('schedule4me', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='id',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='task_id',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='template_id',
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_template',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='schedule_id',
            field=models.IntegerField(default=-1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='user_email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.emailaddress'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_id',
            field=models.IntegerField(default=-1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='is_passive',
            field=models.BooleanField(null=True),
        ),
        migrations.DeleteModel(
            name='Template',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
