# Generated by Django 3.1.2 on 2020-11-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule4me', '0002_auto_20201118_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
