# Generated by Django 3.1.2 on 2020-11-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule4me', '0003_auto_20201118_0446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='user_email',
        ),
        migrations.AddField(
            model_name='schedule',
            name='user',
            field=models.CharField(default=-1, max_length=200),
            preserve_default=False,
        ),
    ]
