# Generated by Django 3.1.2 on 2021-01-14 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule4me', '0004_auto_20201118_0520'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='RawTask',
        ),
        migrations.CreateModel(
            name='OptimizedTask',
            fields=[
                ('task_id', models.IntegerField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=200)),
                ('day', models.CharField(max_length=10)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('schedule_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule4me.schedule')),
            ],
        ),
    ]
