# Generated by Django 3.1.2 on 2021-01-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule4me', '0005_auto_20210114_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optimizedtask',
            name='schedule_id',
        ),
        migrations.RemoveField(
            model_name='rawtask',
            name='schedule_id',
        ),
        migrations.AddField(
            model_name='optimizedtask',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='optimizedtask',
            name='schedule_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='optimizedtask',
            name='user',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawtask',
            name='schedule_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawtask',
            name='user',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
